# Generated by Django 5.0.6 on 2026-05-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('bills', 'Bills/Utilities'), ('family', 'Family'), ('healthcare', 'Healthcare'), ('fuel', 'Fuel'), ('phone', 'Phone/Internet'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('travel', 'Travel'), ('socializing', 'Socializing'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('transport', 'Transportation'), ('housing', 'Housing'), ('miscellaneous', 'Miscellaneous')], default='other', max_length=50),
        ),
    ]
